using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Days
{
    partial class FormSettings
    {
        /// <summary>
        /// Обязательная переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Освободить все используемые ресурсы.
        /// </summary>
        /// <param name="disposing">истинно, если управляемый ресурс должен быть удален; иначе ложно.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(FormSettings));
            this.gbUses = new GroupBox();
            this.chbEveryYear = new CheckBox();
            this.chbUseYears = new CheckBox();
            this.chbUseMonthes = new CheckBox();
            this.chbUseWeeks = new CheckBox();
            this.chbUseDays = new CheckBox();
            this.chbUseHours = new CheckBox();
            this.chbUseMinutes = new CheckBox();
            this.chbUseSeconds = new CheckBox();
            this.nudPreviousDays = new NumericUpDown();
            this.nudNextDays = new NumericUpDown();
            this.nudRecalcDays = new NumericUpDown();
            this.label1 = new Label();
            this.label2 = new Label();
            this.label3 = new Label();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.btOk = new Button();
            this.btCancel = new Button();
            this.gbCalcMethods = new GroupBox();
            this.chbExponent = new CheckBox();
            this.chbSameDigits = new CheckBox();
            this.tbMidNums = new TextBox();
            this.label7 = new Label();
            this.gbUses.SuspendLayout();
            this.nudPreviousDays.BeginInit();
            this.nudNextDays.BeginInit();
            this.nudRecalcDays.BeginInit();
            this.gbCalcMethods.SuspendLayout();
            this.SuspendLayout();
            this.gbUses.Controls.Add((Control)this.chbUseYears);
            this.gbUses.Controls.Add((Control)this.chbUseMonthes);
            this.gbUses.Controls.Add((Control)this.chbUseWeeks);
            this.gbUses.Controls.Add((Control)this.chbUseDays);
            this.gbUses.Controls.Add((Control)this.chbUseHours);
            this.gbUses.Controls.Add((Control)this.chbUseMinutes);
            this.gbUses.Controls.Add((Control)this.chbUseSeconds);
            this.gbUses.Location = new Point(12, 12);
            this.gbUses.Name = "gbUses";
            this.gbUses.Size = new Size(96, 179);
            this.gbUses.TabIndex = 0;
            this.gbUses.TabStop = false;
            this.gbUses.Text = "Использовать";
            this.chbEveryYear.AutoSize = true;
            this.chbEveryYear.Location = new Point(6, 65);
            this.chbEveryYear.Name = "chbEveryYear";
            this.chbEveryYear.Size = new Size(87, 17);
            this.chbEveryYear.TabIndex = 7;
            this.chbEveryYear.Text = "Каждый год";
            this.chbEveryYear.UseVisualStyleBackColor = true;
            this.chbUseYears.AutoSize = true;
            this.chbUseYears.Location = new Point(6, 157);
            this.chbUseYears.Name = "chbUseYears";
            this.chbUseYears.Size = new Size(52, 17);
            this.chbUseYears.TabIndex = 6;
            this.chbUseYears.Text = "Годы";
            this.chbUseYears.UseVisualStyleBackColor = true;
            this.chbUseMonthes.AutoSize = true;
            this.chbUseMonthes.Location = new Point(6, 134);
            this.chbUseMonthes.Name = "chbUseMonthes";
            this.chbUseMonthes.Size = new Size(67, 17);
            this.chbUseMonthes.TabIndex = 5;
            this.chbUseMonthes.Text = "Месяцы";
            this.chbUseMonthes.UseVisualStyleBackColor = true;
            this.chbUseWeeks.AutoSize = true;
            this.chbUseWeeks.Location = new Point(6, 111);
            this.chbUseWeeks.Name = "chbUseWeeks";
            this.chbUseWeeks.Size = new Size(64, 17);
            this.chbUseWeeks.TabIndex = 4;
            this.chbUseWeeks.Text = "Недели";
            this.chbUseWeeks.UseVisualStyleBackColor = true;
            this.chbUseDays.AutoSize = true;
            this.chbUseDays.Location = new Point(6, 88);
            this.chbUseDays.Name = "chbUseDays";
            this.chbUseDays.Size = new Size(47, 17);
            this.chbUseDays.TabIndex = 3;
            this.chbUseDays.Text = "Дни";
            this.chbUseDays.UseVisualStyleBackColor = true;
            this.chbUseHours.AutoSize = true;
            this.chbUseHours.Location = new Point(6, 65);
            this.chbUseHours.Name = "chbUseHours";
            this.chbUseHours.Size = new Size(54, 17);
            this.chbUseHours.TabIndex = 2;
            this.chbUseHours.Text = "Часы";
            this.chbUseHours.UseVisualStyleBackColor = true;
            this.chbUseMinutes.AutoSize = true;
            this.chbUseMinutes.Location = new Point(6, 42);
            this.chbUseMinutes.Name = "chbUseMinutes";
            this.chbUseMinutes.Size = new Size(65, 17);
            this.chbUseMinutes.TabIndex = 1;
            this.chbUseMinutes.Text = "Минуты";
            this.chbUseMinutes.UseVisualStyleBackColor = true;
            this.chbUseSeconds.AutoSize = true;
            this.chbUseSeconds.Location = new Point(6, 19);
            this.chbUseSeconds.Name = "chbUseSeconds";
            this.chbUseSeconds.Size = new Size(70, 17);
            this.chbUseSeconds.TabIndex = 0;
            this.chbUseSeconds.Text = "Секунды";
            this.chbUseSeconds.UseVisualStyleBackColor = true;
            this.nudPreviousDays.Location = new Point(244, 144);
            this.nudPreviousDays.Name = "nudPreviousDays";
            this.nudPreviousDays.Size = new Size(50, 20);
            this.nudPreviousDays.TabIndex = 8;
            this.nudNextDays.Location = new Point(244, 168);
            this.nudNextDays.Name = "nudNextDays";
            this.nudNextDays.Size = new Size(50, 20);
            this.nudNextDays.TabIndex = 9;
            this.nudRecalcDays.Location = new Point(244, 192);
            this.nudRecalcDays.Name = "nudRecalcDays";
            this.nudRecalcDays.Size = new Size(50, 20);
            this.nudRecalcDays.TabIndex = 10;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(112, 148);
            this.label1.Name = "label1";
            this.label1.Size = new Size(126, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "События за последние ";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(112, 172);
            this.label2.Name = "label2";
            this.label2.Size = new Size((int)sbyte.MaxValue, 13);
            this.label2.TabIndex = 5;
            this.label2.Text = "События за следующие";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(112, 196);
            this.label3.Name = "label3";
            this.label3.Size = new Size(110, 13);
            this.label3.TabIndex = 6;
            this.label3.Text = "Перерасчет каждые";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(300, 147);
            this.label4.Name = "label4";
            this.label4.Size = new Size(31, 13);
            this.label4.TabIndex = 7;
            this.label4.Text = "дней";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(300, 170);
            this.label5.Name = "label5";
            this.label5.Size = new Size(31, 13);
            this.label5.TabIndex = 8;
            this.label5.Text = "дней";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(300, 194);
            this.label6.Name = "label6";
            this.label6.Size = new Size(31, 13);
            this.label6.TabIndex = 9;
            this.label6.Text = "дней";
            this.btOk.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.btOk.Location = new Point(172, 224);
            this.btOk.Name = "btOk";
            this.btOk.Size = new Size(75, 23);
            this.btOk.TabIndex = 11;
            this.btOk.Text = "ОК";
            this.btOk.UseVisualStyleBackColor = true;
            this.btOk.Click += new EventHandler(this.btOk_Click);
            this.btCancel.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.btCancel.DialogResult = DialogResult.Cancel;
            this.btCancel.Location = new Point(253, 224);
            this.btCancel.Name = "btCancel";
            this.btCancel.Size = new Size(75, 23);
            this.btCancel.TabIndex = 12;
            this.btCancel.Text = "Отмена";
            this.btCancel.UseVisualStyleBackColor = true;
            this.gbCalcMethods.Controls.Add((Control)this.label7);
            this.gbCalcMethods.Controls.Add((Control)this.tbMidNums);
            this.gbCalcMethods.Controls.Add((Control)this.chbSameDigits);
            this.gbCalcMethods.Controls.Add((Control)this.chbEveryYear);
            this.gbCalcMethods.Controls.Add((Control)this.chbExponent);
            this.gbCalcMethods.Location = new Point(113, 12);
            this.gbCalcMethods.Name = "gbCalcMethods";
            this.gbCalcMethods.Size = new Size(218, 128);
            this.gbCalcMethods.TabIndex = 13;
            this.gbCalcMethods.TabStop = false;
            this.gbCalcMethods.Text = "Формулы";
            this.chbExponent.AutoSize = true;
            this.chbExponent.Location = new Point(6, 19);
            this.chbExponent.Name = "chbExponent";
            this.chbExponent.Size = new Size(84, 17);
            this.chbExponent.TabIndex = 0;
            this.chbExponent.Text = "1..9 * 10 ^ n";
            this.chbExponent.UseVisualStyleBackColor = true;
            this.chbSameDigits.AutoSize = true;
            this.chbSameDigits.Location = new Point(6, 42);
            this.chbSameDigits.Name = "chbSameDigits";
            this.chbSameDigits.Size = new Size(138, 17);
            this.chbSameDigits.TabIndex = 8;
            this.chbSameDigits.Text = "1..9 + .. + (1..9 * 10 ^ n)";
            this.chbSameDigits.UseVisualStyleBackColor = true;
            this.tbMidNums.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.tbMidNums.Location = new Point(6, 100);
            this.tbMidNums.Name = "tbMidNums";
            this.tbMidNums.Size = new Size(206, 20);
            this.tbMidNums.TabIndex = 9;
            this.label7.AutoSize = true;
            this.label7.Location = new Point(4, 83);
            this.label7.Name = "label7";
            this.label7.Size = new Size(159, 13);
            this.label7.TabIndex = 10;
            this.label7.Text = "Промежуточные между 1 и 10";
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.CancelButton = (IButtonControl)this.btCancel;
            this.ClientSize = new Size(339, 263);
            this.Controls.Add((Control)this.gbCalcMethods);
            this.Controls.Add((Control)this.btCancel);
            this.Controls.Add((Control)this.btOk);
            this.Controls.Add((Control)this.label6);
            this.Controls.Add((Control)this.label5);
            this.Controls.Add((Control)this.label4);
            this.Controls.Add((Control)this.label3);
            this.Controls.Add((Control)this.label2);
            this.Controls.Add((Control)this.label1);
            this.Controls.Add((Control)this.nudRecalcDays);
            this.Controls.Add((Control)this.nudNextDays);
            this.Controls.Add((Control)this.nudPreviousDays);
            this.Controls.Add((Control)this.gbUses);
            this.FormBorderStyle = FormBorderStyle.FixedSingle;
            this.Icon = Days.Properties.Resources.Settings;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FormSettings";
            this.StartPosition = FormStartPosition.CenterParent;
            this.Text = "Настройки";
            this.gbUses.ResumeLayout(false);
            this.gbUses.PerformLayout();
            this.nudPreviousDays.EndInit();
            this.nudNextDays.EndInit();
            this.nudRecalcDays.EndInit();
            this.gbCalcMethods.ResumeLayout(false);
            this.gbCalcMethods.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private Settings editedSettings;
        private GroupBox gbUses;
        private CheckBox chbEveryYear;
        private CheckBox chbUseYears;
        private CheckBox chbUseMonthes;
        private CheckBox chbUseWeeks;
        private CheckBox chbUseDays;
        private CheckBox chbUseHours;
        private CheckBox chbUseMinutes;
        private CheckBox chbUseSeconds;
        private NumericUpDown nudPreviousDays;
        private NumericUpDown nudNextDays;
        private NumericUpDown nudRecalcDays;
        private Label label1;
        private Label label2;
        private Label label3;
        private Label label4;
        private Label label5;
        private Label label6;
        private Button btOk;
        private Button btCancel;
        private GroupBox gbCalcMethods;
        private Label label7;
        private TextBox tbMidNums;
        private CheckBox chbSameDigits;
        private CheckBox chbExponent;
    }
}
