using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Days
{
    partial class FormAddContact
    {
        /// <summary>
        /// Обязательная переменная конструктора.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof(FormAddContact));
            this.label1 = new Label();
            this.tbFio = new TextBox();
            this.dtpBirth = new DateTimePicker();
            this.label2 = new Label();
            this.tbInfo = new TextBox();
            this.label3 = new Label();
            this.btCancel = new Button();
            this.btOk = new Button();
            this.label4 = new Label();
            this.label5 = new Label();
            this.label6 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.lYears = new Label();
            this.lMonthes = new Label();
            this.lWeeks = new Label();
            this.lDays = new Label();
            this.lHours = new Label();
            this.lMinutes = new Label();
            this.lSeconds = new Label();
            this.SuspendLayout();
            this.label1.AutoSize = true;
            this.label1.Location = new Point(10, 14);
            this.label1.Name = "label1";
            this.label1.Size = new Size(34, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "ФИО";
            this.tbFio.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            this.tbFio.Location = new Point(97, 10);
            this.tbFio.Name = "tbFio";
            this.tbFio.Size = new Size(270, 20);
            this.tbFio.TabIndex = 0;
            this.dtpBirth.CustomFormat = "dd.MM.yyyy HH:mm";
            this.dtpBirth.Format = DateTimePickerFormat.Custom;
            this.dtpBirth.Location = new Point(97, 35);
            this.dtpBirth.Name = "dtpBirth";
            this.dtpBirth.Size = new Size(125, 20);
            this.dtpBirth.TabIndex = 1;
            this.dtpBirth.ValueChanged += new EventHandler(this.dtpBirth_ValueChanged);
            this.label2.AutoSize = true;
            this.label2.Location = new Point(10, 39);
            this.label2.Name = "label2";
            this.label2.Size = new Size(86, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Дата рождения";
            this.tbInfo.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.tbInfo.Location = new Point(12, 78);
            this.tbInfo.Multiline = true;
            this.tbInfo.Name = "tbInfo";
            this.tbInfo.Size = new Size(225, 232);
            this.tbInfo.TabIndex = 2;
            this.label3.AutoSize = true;
            this.label3.Location = new Point(10, 62);
            this.label3.Name = "label3";
            this.label3.Size = new Size(35, 13);
            this.label3.TabIndex = 5;
            this.label3.Text = "Инфо";
            this.btCancel.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.btCancel.DialogResult = DialogResult.Cancel;
            this.btCancel.Location = new Point(293, 320);
            this.btCancel.Name = "btCancel";
            this.btCancel.Size = new Size(75, 23);
            this.btCancel.TabIndex = 5;
            this.btCancel.Text = "Отмена";
            this.btCancel.UseVisualStyleBackColor = true;
            this.btCancel.Click += new EventHandler(this.btCancel_Click);
            this.btOk.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.btOk.Location = new Point(212, 320);
            this.btOk.Name = "btOk";
            this.btOk.Size = new Size(75, 23);
            this.btOk.TabIndex = 4;
            this.btOk.Text = "OK";
            this.btOk.UseVisualStyleBackColor = true;
            this.btOk.Click += new EventHandler(this.btOk_Click);
            this.label4.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label4.AutoSize = true;
            this.label4.Location = new Point(256, 65);
            this.label4.Name = "label4";
            this.label4.Size = new Size(104, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "На данный момент";
            this.label5.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label5.AutoSize = true;
            this.label5.Location = new Point(243, 80);
            this.label5.Name = "label5";
            this.label5.Size = new Size(46, 13);
            this.label5.TabIndex = 9;
            this.label5.Text = "Секунд:";
            this.label6.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label6.AutoSize = true;
            this.label6.Location = new Point(243, 95);
            this.label6.Name = "label6";
            this.label6.Size = new Size(41, 13);
            this.label6.TabIndex = 10;
            this.label6.Text = "Минут:";
            this.label7.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label7.AutoSize = true;
            this.label7.Location = new Point(243, 110);
            this.label7.Name = "label7";
            this.label7.Size = new Size(42, 13);
            this.label7.TabIndex = 11;
            this.label7.Text = "Часов:";
            this.label8.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label8.AutoSize = true;
            this.label8.Location = new Point(243, 125);
            this.label8.Name = "label8";
            this.label8.Size = new Size(37, 13);
            this.label8.TabIndex = 12;
            this.label8.Text = "Дней:";
            this.label9.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label9.AutoSize = true;
            this.label9.Location = new Point(243, 140);
            this.label9.Name = "label9";
            this.label9.Size = new Size(48, 13);
            this.label9.TabIndex = 13;
            this.label9.Text = "Недель:";
            this.label10.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label10.AutoSize = true;
            this.label10.Location = new Point(243, 155);
            this.label10.Name = "label10";
            this.label10.Size = new Size(55, 13);
            this.label10.TabIndex = 14;
            this.label10.Text = "Месяцев:";
            this.label11.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.label11.AutoSize = true;
            this.label11.Location = new Point(243, 170);
            this.label11.Name = "label11";
            this.label11.Size = new Size(29, 13);
            this.label11.TabIndex = 15;
            this.label11.Text = "Лет:";
            this.lYears.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lYears.AutoSize = true;
            this.lYears.Location = new Point(297, 170);
            this.lYears.Name = "lYears";
            this.lYears.Size = new Size(10, 13);
            this.lYears.TabIndex = 22;
            this.lYears.Text = " ";
            this.lMonthes.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lMonthes.AutoSize = true;
            this.lMonthes.Location = new Point(297, 155);
            this.lMonthes.Name = "lMonthes";
            this.lMonthes.Size = new Size(10, 13);
            this.lMonthes.TabIndex = 21;
            this.lMonthes.Text = " ";
            this.lWeeks.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lWeeks.AutoSize = true;
            this.lWeeks.Location = new Point(297, 140);
            this.lWeeks.Name = "lWeeks";
            this.lWeeks.Size = new Size(10, 13);
            this.lWeeks.TabIndex = 20;
            this.lWeeks.Text = " ";
            this.lDays.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lDays.AutoSize = true;
            this.lDays.Location = new Point(297, 125);
            this.lDays.Name = "lDays";
            this.lDays.Size = new Size(10, 13);
            this.lDays.TabIndex = 19;
            this.lDays.Text = " ";
            this.lHours.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lHours.AutoSize = true;
            this.lHours.Location = new Point(297, 110);
            this.lHours.Name = "lHours";
            this.lHours.Size = new Size(10, 13);
            this.lHours.TabIndex = 18;
            this.lHours.Text = " ";
            this.lMinutes.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lMinutes.AutoSize = true;
            this.lMinutes.Location = new Point(297, 95);
            this.lMinutes.Name = "lMinutes";
            this.lMinutes.Size = new Size(0, 13);
            this.lMinutes.TabIndex = 17;
            this.lSeconds.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            this.lSeconds.AutoSize = true;
            this.lSeconds.Location = new Point(297, 80);
            this.lSeconds.Name = "lSeconds";
            this.lSeconds.Size = new Size(0, 13);
            this.lSeconds.TabIndex = 16;
            this.AcceptButton = (IButtonControl)this.btOk;
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.CancelButton = (IButtonControl)this.btCancel;
            this.ClientSize = new Size(379, 355);
            this.Controls.Add((Control)this.lYears);
            this.Controls.Add((Control)this.lMonthes);
            this.Controls.Add((Control)this.lWeeks);
            this.Controls.Add((Control)this.lDays);
            this.Controls.Add((Control)this.lHours);
            this.Controls.Add((Control)this.lMinutes);
            this.Controls.Add((Control)this.lSeconds);
            this.Controls.Add((Control)this.label11);
            this.Controls.Add((Control)this.label10);
            this.Controls.Add((Control)this.label9);
            this.Controls.Add((Control)this.label8);
            this.Controls.Add((Control)this.label7);
            this.Controls.Add((Control)this.label6);
            this.Controls.Add((Control)this.label5);
            this.Controls.Add((Control)this.label4);
            this.Controls.Add((Control)this.btOk);
            this.Controls.Add((Control)this.btCancel);
            this.Controls.Add((Control)this.label3);
            this.Controls.Add((Control)this.tbInfo);
            this.Controls.Add((Control)this.label2);
            this.Controls.Add((Control)this.dtpBirth);
            this.Controls.Add((Control)this.tbFio);
            this.Controls.Add((Control)this.label1);
            this.Icon = Days.Properties.Resources.AddContact;
            this.MinimumSize = new Size(250, 155);
            this.Name = "FormAddContact";
            this.StartPosition = FormStartPosition.CenterParent;
            this.Text = "Добавляем контакт";
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        public Contact EditedContact;
        public bool Recalc;
        private Label label1;
        private TextBox tbFio;
        private DateTimePicker dtpBirth;
        private Label label2;
        private TextBox tbInfo;
        private Label label3;
        private Button btCancel;
        private Button btOk;
        private Label label4;
        private Label label5;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label lYears;
        private Label lMonthes;
        private Label lWeeks;
        private Label lDays;
        private Label lHours;
        private Label lMinutes;
        private Label lSeconds;
    }
}
